# Generated by Django 3.1.7 on 2021-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210418_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.TextField(default='name', max_length=100),
        ),
    ]
