# Generated by Django 3.1.7 on 2021-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hashtag',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
